services:
  - type: web
    plan: free
    name: leoflow
    env: docker
    #buildCommand: pip install -U -r requirements.txt
    #startCommand: gunicorn app:app & python3 -m Zaid
    repo: https://github.com/a2g-flow/tg-remove-duplicate-file      
    branch: Render
    envVars:
      - key: SESSION 
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false 
      - key: CHAT_LIST
        sync: false
    autoDeploy: false
