services:
  - type: web
    region: frankfurt
    name: vipertgdel
    env: docker
    #buildCommand: pip install -U -r requirements.txt
    #startCommand: gunicorn app:app & python3 -m Zaid
    repo: https://github.com/assc0d3r/tg-remove-duplicate-file      
    branch: master
    envVars:
      - key: SESSION 
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false 
      - key: chat_list
        sync: false
    autoDeploy: false
